const express=require("express");
const cors=require("cors");
const routes=require("./routes/index");
const app=express();
const notFound = require("./middleware/notFound.middleware");
const errorHandler = require("./middleware/error.middleware");
app.use(cors());
app.use(express.json());
app.use("/api/v1", routes);
app.use(notFound);
app.use(errorHandler);
module.exports=app;